[phases.setup]
nixPkgs = ["dotnet-sdk_8", "icu", "zlib", "openssl"]

[phases.build]
# Собираем самодостаточный (self-contained) бинарник для Linux
cmds = ["dotnet publish Helper/Helper.csproj -c Release -r linux-x64 --self-contained true -o out"]

[start]
# Запускаем скрипт
cmd = "bash start.sh"
